---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: site/content/journal
  label: Journal
  create: all
  match: "**/*"
- type: directory
  path: site/content
  label: Pages
  create: all
  match: "*"
upload_dir: uploads
public_path: https://res.cloudinary.com/du7zfoh2l/image/upload
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
instant_preview: true
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.56.3
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: forestryio/hugo:node10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry
  preview_command: npm run build
version: 0.56.3
