baseurl = "/"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
languageCode = "en-us"
languageLang = "en"
sectionPagesMenu = "main"
title = "Be Seated"

[params]
  cloudinary_url = "https://res.cloudinary.com/du7zfoh2l/image/upload"